<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Tessera.Plugins.Gmail</RootNamespace>
    <AssemblyName>Tessera.Plugins.Gmail</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Tessera.Plugin.Abstractions/Tessera.Plugin.Abstractions.csproj" />
  </ItemGroup>

</Project>