using System.Text.Json;
using Microsoft.Data.Sqlite;
using Tessera.Core.Kernel;
using Tessera.Core.Product;

namespace Tessera.Persistence.Sqlite;

public sealed partial class SqliteKernelStore
{
    public async Task<Conversation?> GetConversationAsync(string owner,string id,CancellationToken token=default)
    {
        await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);
        await using var command=connection.CreateCommand();
        command.CommandText="SELECT title,state,model_profile_id,created_at,updated_at,version FROM conversations WHERE owner_principal_id=$owner AND conversation_id=$id AND state<>'DELETED';";
        command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$id",id);
        await using var reader=await command.ExecuteReaderAsync(token).ConfigureAwait(false);
        return await reader.ReadAsync(token).ConfigureAwait(false)?new(owner,id,reader.GetString(0),reader.GetString(1),ReadNullableString(reader,2),ParseTimestamp(reader.GetString(3)),ParseTimestamp(reader.GetString(4)),reader.GetInt64(5)):null;
    }

    public async Task<Conversation?> UpdateConversationAsync(string owner,string id,string? title,string? state,long expectedVersion,CancellationToken token=default)
    {
        if(state is not null and not ("ACTIVE" or "ARCHIVED"))throw new ArgumentException("Conversation state is invalid.",nameof(state));
        await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();
        command.CommandText="UPDATE conversations SET title=COALESCE($title,title),state=COALESCE($state,state),updated_at=$now,version=version+1 WHERE owner_principal_id=$owner AND conversation_id=$id AND version=$version AND state<>'DELETED';";
        command.Parameters.AddWithValue("$title",string.IsNullOrWhiteSpace(title)?DBNull.Value:title.Trim());command.Parameters.AddWithValue("$state",(object?)state??DBNull.Value);command.Parameters.AddWithValue("$now",FormatTimestamp(DateTimeOffset.UtcNow));command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$id",id);command.Parameters.AddWithValue("$version",expectedVersion);
        if(await command.ExecuteNonQueryAsync(token).ConfigureAwait(false)!=1)return null;
        return await GetConversationAsync(owner,id,token).ConfigureAwait(false);
    }

    public async Task<bool> DeleteConversationAsync(string owner,string id,long expectedVersion,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="UPDATE conversations SET state='DELETED',updated_at=$now,version=version+1 WHERE owner_principal_id=$owner AND conversation_id=$id AND version=$version AND state IN ('ACTIVE','ARCHIVED');";command.Parameters.AddWithValue("$now",FormatTimestamp(DateTimeOffset.UtcNow));command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$id",id);command.Parameters.AddWithValue("$version",expectedVersion);return await command.ExecuteNonQueryAsync(token).ConfigureAwait(false)==1;}

    public async Task<long?> StopExecutionAsync(string owner,string conversation,string execution,long expectedVersion,DateTimeOffset now,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="UPDATE execution_controls SET state='STOPPED',updated_at=$now,version=version+1 WHERE owner_principal_id=$owner AND conversation_id=$conversation AND execution_id=$execution AND state='RUNNING' AND version=$version RETURNING version;";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$conversation",conversation);command.Parameters.AddWithValue("$execution",execution);command.Parameters.AddWithValue("$version",expectedVersion);command.Parameters.AddWithValue("$now",FormatTimestamp(now));var value=await command.ExecuteScalarAsync(token).ConfigureAwait(false);return value is null?null:Convert.ToInt64(value,System.Globalization.CultureInfo.InvariantCulture);}

    public async Task StartExecutionAsync(string owner,string conversation,string execution,string? message,DateTimeOffset now,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="INSERT INTO execution_controls(owner_principal_id,execution_id,conversation_id,message_id,state,updated_at,version) VALUES($owner,$execution,$conversation,$message,'RUNNING',$now,1);";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$execution",execution);command.Parameters.AddWithValue("$conversation",conversation);command.Parameters.AddWithValue("$message",(object?)message??DBNull.Value);command.Parameters.AddWithValue("$now",FormatTimestamp(now));await command.ExecuteNonQueryAsync(token).ConfigureAwait(false);}

    public async Task<bool> AcceptChatExecutionAsync(ChatMessage userMessage,string executionId,string modelProfileId,string idempotencyKey,PublicExecutionEvent initialEvent,CancellationToken token=default)
    {
        await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var transaction=(SqliteTransaction)await connection.BeginTransactionAsync(token).ConfigureAwait(false);
        await using(var message=connection.CreateCommand()){message.Transaction=transaction;message.CommandText="""
            INSERT OR IGNORE INTO messages(owner_principal_id,message_id,conversation_id,role,status,retry_of,created_at,completed_at,version)
            SELECT $owner,$id,$conversation,$role,$status,$retry,$created,$completed,$version
            FROM conversations WHERE owner_principal_id=$owner AND conversation_id=$conversation AND state='ACTIVE';
            """;message.Parameters.AddWithValue("$owner",userMessage.OwnerPrincipalId);message.Parameters.AddWithValue("$id",userMessage.MessageId);message.Parameters.AddWithValue("$conversation",userMessage.ConversationId);message.Parameters.AddWithValue("$role",userMessage.Role);message.Parameters.AddWithValue("$status",userMessage.Status);message.Parameters.AddWithValue("$retry",(object?)userMessage.RetryOf??DBNull.Value);message.Parameters.AddWithValue("$created",FormatTimestamp(userMessage.CreatedAt));message.Parameters.AddWithValue("$completed",userMessage.CompletedAt is null?DBNull.Value:FormatTimestamp(userMessage.CompletedAt.Value));message.Parameters.AddWithValue("$version",userMessage.Version);if(await message.ExecuteNonQueryAsync(token).ConfigureAwait(false)!=1){await transaction.RollbackAsync(token).ConfigureAwait(false);return false;}}
        foreach(var part in userMessage.Parts){await using var insert=connection.CreateCommand();insert.Transaction=transaction;insert.CommandText="INSERT INTO message_parts(owner_principal_id,part_id,message_id,sequence,kind,text,capability_call_id,capability_result_id,action_id,evidence_refs_json,error_code) VALUES($owner,$part,$message,$sequence,$kind,$text,$call,$result,$action,$evidence,$error);";insert.Parameters.AddWithValue("$owner",userMessage.OwnerPrincipalId);insert.Parameters.AddWithValue("$part",part.PartId);insert.Parameters.AddWithValue("$message",userMessage.MessageId);insert.Parameters.AddWithValue("$sequence",part.Sequence);insert.Parameters.AddWithValue("$kind",part.Kind);insert.Parameters.AddWithValue("$text",(object?)part.Text??DBNull.Value);insert.Parameters.AddWithValue("$call",(object?)part.CapabilityCallId??DBNull.Value);insert.Parameters.AddWithValue("$result",(object?)part.CapabilityResultId??DBNull.Value);insert.Parameters.AddWithValue("$action",(object?)part.ActionId??DBNull.Value);insert.Parameters.AddWithValue("$evidence",JsonSerializer.Serialize(part.EvidenceRefs??[]));insert.Parameters.AddWithValue("$error",(object?)part.ErrorCode??DBNull.Value);await insert.ExecuteNonQueryAsync(token).ConfigureAwait(false);}
        await using(var control=connection.CreateCommand()){control.Transaction=transaction;control.CommandText="INSERT INTO execution_controls(owner_principal_id,execution_id,conversation_id,message_id,state,updated_at,version,model_profile_id,idempotency_key) VALUES($owner,$execution,$conversation,$message,'RUNNING',$now,1,$profile,$key);";control.Parameters.AddWithValue("$owner",userMessage.OwnerPrincipalId);control.Parameters.AddWithValue("$execution",executionId);control.Parameters.AddWithValue("$conversation",userMessage.ConversationId);control.Parameters.AddWithValue("$message",userMessage.MessageId);control.Parameters.AddWithValue("$now",FormatTimestamp(userMessage.CreatedAt));control.Parameters.AddWithValue("$profile",modelProfileId);control.Parameters.AddWithValue("$key",idempotencyKey);await control.ExecuteNonQueryAsync(token).ConfigureAwait(false);}
        await using(var eventCommand=connection.CreateCommand()){eventCommand.Transaction=transaction;eventCommand.CommandText="INSERT INTO execution_events(owner_principal_id,event_id,execution_id,sequence,event_type,occurred_at,message_id,capability_call_id,action_id,data_json) VALUES($owner,$event,$execution,$sequence,$type,$at,$message,$call,$action,$data);";eventCommand.Parameters.AddWithValue("$owner",initialEvent.OwnerPrincipalId);eventCommand.Parameters.AddWithValue("$event",initialEvent.EventId);eventCommand.Parameters.AddWithValue("$execution",initialEvent.ExecutionId);eventCommand.Parameters.AddWithValue("$sequence",initialEvent.Sequence);eventCommand.Parameters.AddWithValue("$type",initialEvent.EventType);eventCommand.Parameters.AddWithValue("$at",FormatTimestamp(initialEvent.OccurredAt));eventCommand.Parameters.AddWithValue("$message",(object?)initialEvent.MessageId??DBNull.Value);eventCommand.Parameters.AddWithValue("$call",(object?)initialEvent.CapabilityCallId??DBNull.Value);eventCommand.Parameters.AddWithValue("$action",(object?)initialEvent.ActionId??DBNull.Value);eventCommand.Parameters.AddWithValue("$data",initialEvent.DataJson);await eventCommand.ExecuteNonQueryAsync(token).ConfigureAwait(false);}
        await transaction.CommitAsync(token).ConfigureAwait(false);return true;
    }

    public async Task<bool> AcceptChatRetryExecutionAsync(string owner,string conversationId,string userMessageId,string executionId,string modelProfileId,string idempotencyKey,PublicExecutionEvent initialEvent,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var transaction=(SqliteTransaction)await connection.BeginTransactionAsync(token).ConfigureAwait(false);await using(var control=connection.CreateCommand()){control.Transaction=transaction;control.CommandText="""
        INSERT OR IGNORE INTO execution_controls(owner_principal_id,execution_id,conversation_id,message_id,state,updated_at,version,model_profile_id,idempotency_key)
        SELECT $owner,$execution,$conversation,$message,'RUNNING',$now,1,$profile,$key FROM messages
        WHERE owner_principal_id=$owner AND message_id=$message AND conversation_id=$conversation AND role='USER';
        """;control.Parameters.AddWithValue("$owner",owner);control.Parameters.AddWithValue("$execution",executionId);control.Parameters.AddWithValue("$conversation",conversationId);control.Parameters.AddWithValue("$message",userMessageId);control.Parameters.AddWithValue("$now",FormatTimestamp(initialEvent.OccurredAt));control.Parameters.AddWithValue("$profile",modelProfileId);control.Parameters.AddWithValue("$key",idempotencyKey);if(await control.ExecuteNonQueryAsync(token).ConfigureAwait(false)!=1){await transaction.RollbackAsync(token).ConfigureAwait(false);return false;}}await using(var eventCommand=connection.CreateCommand()){eventCommand.Transaction=transaction;eventCommand.CommandText="INSERT INTO execution_events(owner_principal_id,event_id,execution_id,sequence,event_type,occurred_at,message_id,capability_call_id,action_id,data_json) VALUES($owner,$event,$execution,$sequence,$type,$at,$message,NULL,NULL,$data);";eventCommand.Parameters.AddWithValue("$owner",owner);eventCommand.Parameters.AddWithValue("$event",initialEvent.EventId);eventCommand.Parameters.AddWithValue("$execution",executionId);eventCommand.Parameters.AddWithValue("$sequence",initialEvent.Sequence);eventCommand.Parameters.AddWithValue("$type",initialEvent.EventType);eventCommand.Parameters.AddWithValue("$at",FormatTimestamp(initialEvent.OccurredAt));eventCommand.Parameters.AddWithValue("$message",userMessageId);eventCommand.Parameters.AddWithValue("$data",initialEvent.DataJson);await eventCommand.ExecuteNonQueryAsync(token).ConfigureAwait(false);}await transaction.CommitAsync(token).ConfigureAwait(false);return true;}

    public async Task<bool> IsExecutionStoppedAsync(string owner,string execution,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="SELECT 1 FROM execution_controls WHERE owner_principal_id=$owner AND execution_id=$execution AND state='STOPPED';";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$execution",execution);return await command.ExecuteScalarAsync(token).ConfigureAwait(false)is not null;}

    public async Task<bool> ExecutionBelongsToConversationAsync(string owner,string conversation,string execution,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="SELECT 1 FROM execution_controls WHERE owner_principal_id=$owner AND conversation_id=$conversation AND execution_id=$execution;";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$conversation",conversation);command.Parameters.AddWithValue("$execution",execution);return await command.ExecuteScalarAsync(token).ConfigureAwait(false)is not null;}

    public async Task<string?> GetExecutionModelProfileAsync(string owner,string execution,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="SELECT model_profile_id FROM execution_controls WHERE owner_principal_id=$owner AND execution_id=$execution;";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$execution",execution);return await command.ExecuteScalarAsync(token).ConfigureAwait(false) as string;}

    public async Task CompleteExecutionAsync(string owner,string execution,string state,DateTimeOffset now,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="UPDATE execution_controls SET state=$state,updated_at=$now,version=version+1 WHERE owner_principal_id=$owner AND execution_id=$execution AND state='RUNNING';";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$execution",execution);command.Parameters.AddWithValue("$state",state);command.Parameters.AddWithValue("$now",FormatTimestamp(now));await command.ExecuteNonQueryAsync(token).ConfigureAwait(false);}

    public async Task<IReadOnlyList<PendingChatExecution>> ListPendingChatExecutionsAsync(CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="""
        SELECT control.owner_principal_id,control.execution_id,control.conversation_id,control.message_id,part.text,control.model_profile_id,control.idempotency_key
        FROM execution_controls control
        JOIN conversations conversation ON conversation.owner_principal_id=control.owner_principal_id AND conversation.conversation_id=control.conversation_id
        JOIN message_parts part ON part.owner_principal_id=control.owner_principal_id AND part.message_id=control.message_id AND part.kind='TEXT'
        WHERE control.state='RUNNING' AND control.message_id IS NOT NULL AND control.model_profile_id IS NOT NULL AND control.idempotency_key IS NOT NULL
        ORDER BY control.updated_at,control.execution_id LIMIT 100;
        """;var values=new List<PendingChatExecution>();await using var reader=await command.ExecuteReaderAsync(token).ConfigureAwait(false);while(await reader.ReadAsync(token).ConfigureAwait(false))values.Add(new(reader.GetString(0),reader.GetString(1),reader.GetString(2),reader.GetString(3),reader.GetString(4),reader.GetString(5),reader.GetString(6)));return values.AsReadOnly();}

    public async Task<PluginInstallation?> GetPluginInstallationAsync(string owner,string id,string version,CancellationToken token=default)
        =>(await ListPluginInstallationsAsync(owner,token).ConfigureAwait(false)).SingleOrDefault(item=>item.PluginId==id&&item.PluginVersion==version);

    public async Task<PluginInstallation?> SetPluginConfigurationAsync(string owner,string id,string version,long expectedVersion,string configurationJson,CancellationToken token=default)
    {var installation=await GetPluginInstallationAsync(owner,id,version,token).ConfigureAwait(false);if(installation is null)return null;ValidateNonSecretConfiguration(configurationJson,ReadConfigurationFields(installation.ManifestJson));await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="UPDATE plugin_installations SET configuration_json=$configuration,updated_at=$now,version=version+1 WHERE owner_principal_id=$owner AND plugin_id=$id AND plugin_version=$pluginVersion AND version=$version AND removed=0;";command.Parameters.AddWithValue("$configuration",configurationJson);command.Parameters.AddWithValue("$now",FormatTimestamp(DateTimeOffset.UtcNow));command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$id",id);command.Parameters.AddWithValue("$pluginVersion",version);command.Parameters.AddWithValue("$version",expectedVersion);if(await command.ExecuteNonQueryAsync(token).ConfigureAwait(false)!=1)return null;return await GetPluginInstallationAsync(owner,id,version,token).ConfigureAwait(false);}

    public async Task<string?> RemovePluginAsync(string owner,string id,string version,long expectedVersion,CancellationToken token=default)
    {
        var installation=await GetPluginInstallationAsync(owner,id,version,token).ConfigureAwait(false);if(installation is null)return "version_conflict";
        await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);
        await using(var guard=connection.CreateCommand())
        {guard.CommandText="""
            SELECT 1 WHERE EXISTS(SELECT 1 FROM connected_accounts WHERE owner_principal_id=$owner AND plugin_id=$id AND plugin_version=$pluginVersion AND lifecycle<>'REVOKED')
              OR EXISTS(SELECT 1 FROM durable_execution_requests WHERE owner_principal_id=$owner AND plugin_id=$id AND plugin_version=$pluginVersion)
              OR EXISTS(SELECT 1 FROM actions WHERE owner_principal_id=$owner AND plugin_id=$id AND plugin_version=$pluginVersion AND state IN ('PROPOSED','AUTHORIZED','STARTED','RECONCILIATION_REQUIRED'));
            """;guard.Parameters.AddWithValue("$owner",owner);guard.Parameters.AddWithValue("$id",id);guard.Parameters.AddWithValue("$pluginVersion",version);if(await guard.ExecuteScalarAsync(token).ConfigureAwait(false)is not null)return "plugin_in_use";}
        var capabilities=ReadManifestCapabilities(installation.ManifestJson);
        if(capabilities.Count>0)
        {await using var grants=connection.CreateCommand();grants.CommandText="SELECT c.capability_id,c.capability_version FROM job_capability_grants c JOIN jobs j ON j.owner_principal_id=c.owner_principal_id AND j.job_id=c.job_id WHERE c.owner_principal_id=$owner AND j.desired_state<>'CANCELED';";grants.Parameters.AddWithValue("$owner",owner);await using var reader=await grants.ExecuteReaderAsync(token).ConfigureAwait(false);while(await reader.ReadAsync(token).ConfigureAwait(false))if(capabilities.Contains((reader.GetString(0),reader.GetString(1))))return "plugin_in_use";}
        await using var command=connection.CreateCommand();command.CommandText="UPDATE plugin_installations SET enabled=0,removed=1,updated_at=$now,version=version+1 WHERE owner_principal_id=$owner AND plugin_id=$id AND plugin_version=$pluginVersion AND version=$version AND removed=0;";command.Parameters.AddWithValue("$now",FormatTimestamp(DateTimeOffset.UtcNow));command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$id",id);command.Parameters.AddWithValue("$pluginVersion",version);command.Parameters.AddWithValue("$version",expectedVersion);return await command.ExecuteNonQueryAsync(token).ConfigureAwait(false)==1?null:"version_conflict";
    }

    public async Task<ActionRecord?> CancelActionAsync(string owner,string id,long expectedVersion,DateTimeOffset now,CancellationToken token=default)
    {var action=await GetActionAsync(owner,id,token).ConfigureAwait(false);if(action is null||action.Version!=expectedVersion||!ActionRecord.CanTransition(action.State,ActionState.Canceled))return null;var canceled=action.TransitionTo(ActionState.Canceled,now);return await UpdateAsync(owner,canceled,expectedVersion,token).ConfigureAwait(false)?canceled:null;}

    public async Task<ProductSettings> GetSettingsAsync(string owner,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="SELECT default_chat_model_profile_id,default_lightweight_model_profile_id,timezone,approval_defaults_json,memory_controls_json,version FROM product_settings WHERE owner_principal_id=$owner AND settings_id='default';";command.Parameters.AddWithValue("$owner",owner);await using var reader=await command.ExecuteReaderAsync(token).ConfigureAwait(false);return await reader.ReadAsync(token).ConfigureAwait(false)?new(owner,ReadNullableString(reader,0),ReadNullableString(reader,1),reader.GetString(2),reader.GetString(3),reader.GetString(4),reader.GetInt64(5)):new(owner,null,null,"UTC","{}","{}",1);}

    public async Task<ProductSettings?> UpdateSettingsAsync(string owner,string? chat,string? lightweight,string? timezone,string? approvals,string? memory,long expectedVersion,CancellationToken token=default)
    {
        _=TimeZoneInfo.FindSystemTimeZoneById(timezone??"UTC");
        foreach(var json in new[]{approvals,memory}.Where(value=>value is not null)){using var document=JsonDocument.Parse(json!);ProductContentValidation.Json(document.RootElement,"settings",16*1024);}
        if(chat is not null&&await GetModelProfileAsync(owner,chat,token).ConfigureAwait(false) is null)throw new ArgumentException("Default Chat model profile is invalid.",nameof(chat));
        if(lightweight is not null&&await GetModelProfileAsync(owner,lightweight,token).ConfigureAwait(false) is null)throw new ArgumentException("Default lightweight model profile is invalid.",nameof(lightweight));
        await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var transaction=(SqliteTransaction)await connection.BeginTransactionAsync(token).ConfigureAwait(false);
        await using var command=connection.CreateCommand();command.Transaction=transaction;command.CommandText="""
            INSERT INTO product_settings(owner_principal_id,settings_id,default_chat_model_profile_id,default_lightweight_model_profile_id,timezone,approval_defaults_json,memory_controls_json,updated_at,version)
            SELECT $owner,'default',$chat,$lightweight,COALESCE($timezone,'UTC'),COALESCE($approvals,'{}'),COALESCE($memory,'{}'),$now,2 WHERE $expected=1 AND NOT EXISTS(SELECT 1 FROM product_settings WHERE owner_principal_id=$owner AND settings_id='default')
            ON CONFLICT(owner_principal_id,settings_id) DO UPDATE SET default_chat_model_profile_id=COALESCE($chat,default_chat_model_profile_id),default_lightweight_model_profile_id=COALESCE($lightweight,default_lightweight_model_profile_id),timezone=COALESCE($timezone,timezone),approval_defaults_json=COALESCE($approvals,approval_defaults_json),memory_controls_json=COALESCE($memory,memory_controls_json),updated_at=$now,version=product_settings.version+1 WHERE product_settings.version=$expected;
            """;command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$chat",(object?)chat??DBNull.Value);command.Parameters.AddWithValue("$lightweight",(object?)lightweight??DBNull.Value);command.Parameters.AddWithValue("$timezone",(object?)timezone??DBNull.Value);command.Parameters.AddWithValue("$approvals",(object?)approvals??DBNull.Value);command.Parameters.AddWithValue("$memory",(object?)memory??DBNull.Value);command.Parameters.AddWithValue("$now",FormatTimestamp(DateTimeOffset.UtcNow));command.Parameters.AddWithValue("$expected",expectedVersion);if(await command.ExecuteNonQueryAsync(token).ConfigureAwait(false)!=1)return null;await transaction.CommitAsync(token).ConfigureAwait(false);return await GetSettingsAsync(owner,token).ConfigureAwait(false);
    }

    public async Task<AssertionRecord?> StopUsingMemoryAsync(string owner,string id,DateTimeOffset now,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="UPDATE assertions SET epistemic_status='Superseded',valid_to=$now,superseded_at=$now WHERE owner_principal_id=$owner AND assertion_id=$id AND epistemic_status='Current';";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$id",id);command.Parameters.AddWithValue("$now",FormatTimestamp(now));if(await command.ExecuteNonQueryAsync(token).ConfigureAwait(false)!=1)return null;return await ((IAssertionRepository)this).GetAsync(owner,id,token).ConfigureAwait(false);}

    public async Task<IReadOnlyList<AssertionRecord>> ListMemoryAsync(string owner,bool includeHistory,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText=$"{AssertionSelect} WHERE owner_principal_id=$owner AND ($history=1 OR epistemic_status='Current') ORDER BY valid_from DESC,assertion_id LIMIT 100;";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$history",includeHistory);return await ReadAssertionsAsync(command,token).ConfigureAwait(false);}

    public async Task<IReadOnlyList<JobRunOutput>> ListJobRunOutputsAsync(string owner,string runId,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="SELECT output_ref,kind,media_type,summary,text,truncated,created_at FROM job_outputs WHERE owner_principal_id=$owner AND run_id=$run ORDER BY created_at,output_ref LIMIT 100;";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$run",runId);var values=new List<JobRunOutput>();await using var reader=await command.ExecuteReaderAsync(token).ConfigureAwait(false);while(await reader.ReadAsync(token).ConfigureAwait(false))values.Add(new(reader.GetString(0),runId,reader.GetString(1),reader.GetString(2),reader.GetString(3),ReadNullableString(reader,4),reader.GetBoolean(5),ParseTimestamp(reader.GetString(6))));return values.AsReadOnly();}

    public async Task AddJobRunOutputAsync(string owner,JobRunOutput output,CancellationToken token=default)
    {var summary=ProductContentValidation.Text(output.Summary,nameof(output.Summary),512);var text=output.Text is null?null:ProductContentValidation.Text(output.Text,nameof(output.Text),16384);await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="INSERT INTO job_outputs(owner_principal_id,output_ref,run_id,kind,media_type,summary,text,truncated,created_at) VALUES($owner,$ref,$run,$kind,$media,$summary,$text,$truncated,$created);";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$ref",output.OutputRef);command.Parameters.AddWithValue("$run",output.RunId);command.Parameters.AddWithValue("$kind",output.Kind);command.Parameters.AddWithValue("$media",output.MediaType);command.Parameters.AddWithValue("$summary",summary);command.Parameters.AddWithValue("$text",(object?)text??DBNull.Value);command.Parameters.AddWithValue("$truncated",output.Truncated);command.Parameters.AddWithValue("$created",FormatTimestamp(output.CreatedAt));await command.ExecuteNonQueryAsync(token).ConfigureAwait(false);}

    public async Task<IReadOnlyList<JobRunCheckpoint>> ListJobRunCheckpointsAsync(string owner,string runId,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="SELECT sequence,step,state_json,fence,created_at FROM job_run_checkpoints WHERE owner_principal_id=$owner AND run_id=$run ORDER BY sequence LIMIT 100;";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$run",runId);var values=new List<JobRunCheckpoint>();await using var reader=await command.ExecuteReaderAsync(token).ConfigureAwait(false);while(await reader.ReadAsync(token).ConfigureAwait(false))values.Add(new(reader.GetInt64(0),reader.GetString(1),reader.GetString(2),reader.GetInt64(3),ParseTimestamp(reader.GetString(4))));return values.AsReadOnly();}

    private static void ValidateNonSecretConfiguration(string json,IReadOnlyCollection<string> allowedFields)
    {using var document=JsonDocument.Parse(json);if(document.RootElement.ValueKind!=JsonValueKind.Object)throw new ArgumentException("Plugin configuration must be an object.");ProductContentValidation.Json(document.RootElement,nameof(json),16*1024);foreach(var property in document.RootElement.EnumerateObject()){var name=property.Name.ToLowerInvariant();if(!allowedFields.Contains(property.Name,StringComparer.Ordinal)||name.Contains("secret",StringComparison.Ordinal)||name.Contains("token",StringComparison.Ordinal)||name.Contains("password",StringComparison.Ordinal)||name.Contains("credential",StringComparison.Ordinal)||name.EndsWith("key",StringComparison.Ordinal))throw new ArgumentException("Unknown or secret-like plugin configuration fields are not accepted.");}}

    private static string[] ReadConfigurationFields(string manifestJson)
    {using var document=JsonDocument.Parse(manifestJson);if(!document.RootElement.TryGetProperty("configurationFields",out var fields)&&!document.RootElement.TryGetProperty("ConfigurationFields",out fields))return Array.Empty<string>();return fields.ValueKind==JsonValueKind.Array?fields.EnumerateArray().Select(item=>item.GetString()).Where(item=>item is not null).Cast<string>().ToArray():throw new ArgumentException("Plugin configuration declaration is invalid.");}

    private static HashSet<(string Id,string Version)> ReadManifestCapabilities(string manifestJson)
    {using var document=JsonDocument.Parse(manifestJson);if(!document.RootElement.TryGetProperty("capabilities",out var values)&&!document.RootElement.TryGetProperty("Capabilities",out values))return [];var result=new HashSet<(string,string)>();foreach(var item in values.EnumerateArray()){var id=item.TryGetProperty("id",out var lowerId)?lowerId.GetString():item.GetProperty("Id").GetString();var version=item.TryGetProperty("version",out var lowerVersion)?lowerVersion.GetString():item.GetProperty("Version").GetString();if(id is not null&&version is not null)result.Add((id,version));}return result;}
}