using System.Text.Json;
using Tessera.Core.Product;

namespace Tessera.Persistence.Sqlite;

public sealed partial class SqliteKernelStore
{
    public async Task AddConversationAsync(Conversation conversation, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        await using var command = connection.CreateCommand(); command.CommandText = """
            INSERT INTO conversations(owner_principal_id,conversation_id,title,state,model_profile_id,created_at,updated_at,version)
            VALUES($owner,$id,$title,$state,$profile,$created,$updated,$version);
            """;
        command.Parameters.AddWithValue("$owner",conversation.OwnerPrincipalId); command.Parameters.AddWithValue("$id",conversation.ConversationId);
        command.Parameters.AddWithValue("$title",conversation.Title); command.Parameters.AddWithValue("$state",conversation.State);
        command.Parameters.AddWithValue("$profile",(object?)conversation.ModelProfileId ?? DBNull.Value);
        command.Parameters.AddWithValue("$created",FormatTimestamp(conversation.CreatedAt)); command.Parameters.AddWithValue("$updated",FormatTimestamp(conversation.UpdatedAt));
        command.Parameters.AddWithValue("$version",conversation.Version); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }

    public async Task<bool> ReplaceConversationGrantsAsync(string owner,string conversationId,long expectedVersion,IReadOnlyList<string> accountIds,IReadOnlyList<(string Id,string Version)> capabilities,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var transaction=(Microsoft.Data.Sqlite.SqliteTransaction)await connection.BeginTransactionAsync(token).ConfigureAwait(false);await using(var update=connection.CreateCommand()){update.Transaction=transaction;update.CommandText="UPDATE conversations SET version=version+1,updated_at=$now WHERE owner_principal_id=$owner AND conversation_id=$conversation AND version=$version AND state='ACTIVE';";update.Parameters.AddWithValue("$now",FormatTimestamp(DateTimeOffset.UtcNow));update.Parameters.AddWithValue("$owner",owner);update.Parameters.AddWithValue("$conversation",conversationId);update.Parameters.AddWithValue("$version",expectedVersion);if(await update.ExecuteNonQueryAsync(token).ConfigureAwait(false)!=1)return false;}foreach(var table in new[]{"conversation_account_grants","conversation_capability_grants"}){await using var delete=connection.CreateCommand();delete.Transaction=transaction;delete.CommandText=$"DELETE FROM {table} WHERE owner_principal_id=$owner AND conversation_id=$conversation;";delete.Parameters.AddWithValue("$owner",owner);delete.Parameters.AddWithValue("$conversation",conversationId);await delete.ExecuteNonQueryAsync(token).ConfigureAwait(false);}foreach(var account in accountIds.Distinct(StringComparer.Ordinal)){await using var insert=connection.CreateCommand();insert.Transaction=transaction;insert.CommandText="INSERT INTO conversation_account_grants(owner_principal_id,conversation_id,account_id) VALUES($owner,$conversation,$account);";insert.Parameters.AddWithValue("$owner",owner);insert.Parameters.AddWithValue("$conversation",conversationId);insert.Parameters.AddWithValue("$account",account);await insert.ExecuteNonQueryAsync(token).ConfigureAwait(false);}foreach(var capability in capabilities.Distinct()){await using var insert=connection.CreateCommand();insert.Transaction=transaction;insert.CommandText="INSERT INTO conversation_capability_grants(owner_principal_id,conversation_id,capability_id,capability_version) VALUES($owner,$conversation,$capability,$version);";insert.Parameters.AddWithValue("$owner",owner);insert.Parameters.AddWithValue("$conversation",conversationId);insert.Parameters.AddWithValue("$capability",capability.Id);insert.Parameters.AddWithValue("$version",capability.Version);await insert.ExecuteNonQueryAsync(token).ConfigureAwait(false);}await transaction.CommitAsync(token).ConfigureAwait(false);return true;}

    public async Task<(IReadOnlyList<string> Accounts,IReadOnlyList<(string Id,string Version)> Capabilities)> GetConversationGrantsAsync(string owner,string conversationId,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);var accounts=new List<string>();await using(var command=connection.CreateCommand()){command.CommandText="SELECT account_id FROM conversation_account_grants WHERE owner_principal_id=$owner AND conversation_id=$conversation ORDER BY account_id;";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$conversation",conversationId);await using var reader=await command.ExecuteReaderAsync(token).ConfigureAwait(false);while(await reader.ReadAsync(token).ConfigureAwait(false))accounts.Add(reader.GetString(0));}var capabilities=new List<(string,string)>();await using(var command=connection.CreateCommand()){command.CommandText="SELECT capability_id,capability_version FROM conversation_capability_grants WHERE owner_principal_id=$owner AND conversation_id=$conversation ORDER BY capability_id,capability_version;";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$conversation",conversationId);await using var reader=await command.ExecuteReaderAsync(token).ConfigureAwait(false);while(await reader.ReadAsync(token).ConfigureAwait(false))capabilities.Add((reader.GetString(0),reader.GetString(1)));}return(accounts.AsReadOnly(),capabilities.AsReadOnly());}

    public async Task<IReadOnlyList<Conversation>> ListConversationsAsync(string owner, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        await using var command = connection.CreateCommand(); command.CommandText = "SELECT conversation_id,title,state,model_profile_id,created_at,updated_at,version FROM conversations WHERE owner_principal_id=$owner AND state<>'DELETED' ORDER BY updated_at DESC,conversation_id;";
        command.Parameters.AddWithValue("$owner",owner); var values = new List<Conversation>();
        await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
        while(await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) values.Add(new(owner,reader.GetString(0),reader.GetString(1),reader.GetString(2),ReadNullableString(reader,3),ParseTimestamp(reader.GetString(4)),ParseTimestamp(reader.GetString(5)),reader.GetInt64(6)));
        return values.AsReadOnly();
    }

    public async Task AddMessageAsync(ChatMessage message, CancellationToken cancellationToken = default)
    {
        await using var connection = await OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        await using var transaction = await connection.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
        await using(var command=connection.CreateCommand()) { command.Transaction=(Microsoft.Data.Sqlite.SqliteTransaction)transaction; command.CommandText="""
            INSERT INTO messages(owner_principal_id,message_id,conversation_id,role,status,retry_of,created_at,completed_at,version)
            VALUES($owner,$id,$conversation,$role,$status,$retry,$created,$completed,$version);
            """; command.Parameters.AddWithValue("$owner",message.OwnerPrincipalId); command.Parameters.AddWithValue("$id",message.MessageId); command.Parameters.AddWithValue("$conversation",message.ConversationId); command.Parameters.AddWithValue("$role",message.Role); command.Parameters.AddWithValue("$status",message.Status); command.Parameters.AddWithValue("$retry",(object?)message.RetryOf??DBNull.Value); command.Parameters.AddWithValue("$created",FormatTimestamp(message.CreatedAt)); command.Parameters.AddWithValue("$completed",message.CompletedAt is null?DBNull.Value:FormatTimestamp(message.CompletedAt.Value)); command.Parameters.AddWithValue("$version",message.Version); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }
        foreach(var part in message.Parts) { await using var command=connection.CreateCommand(); command.Transaction=(Microsoft.Data.Sqlite.SqliteTransaction)transaction; command.CommandText="""
            INSERT INTO message_parts(owner_principal_id,part_id,message_id,sequence,kind,text,capability_call_id,capability_result_id,action_id,evidence_refs_json,error_code)
            VALUES($owner,$id,$message,$sequence,$kind,$text,$call,$result,$action,$evidence,$error);
            """; command.Parameters.AddWithValue("$owner",message.OwnerPrincipalId); command.Parameters.AddWithValue("$id",part.PartId); command.Parameters.AddWithValue("$message",message.MessageId); command.Parameters.AddWithValue("$sequence",part.Sequence); command.Parameters.AddWithValue("$kind",part.Kind); command.Parameters.AddWithValue("$text",(object?)part.Text??DBNull.Value); command.Parameters.AddWithValue("$call",(object?)part.CapabilityCallId??DBNull.Value); command.Parameters.AddWithValue("$result",(object?)part.CapabilityResultId??DBNull.Value); command.Parameters.AddWithValue("$action",(object?)part.ActionId??DBNull.Value); command.Parameters.AddWithValue("$evidence",Serialize(part.EvidenceRefs??[])); command.Parameters.AddWithValue("$error",(object?)part.ErrorCode??DBNull.Value); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }
        await transaction.CommitAsync(cancellationToken).ConfigureAwait(false);
    }

    public async Task<IReadOnlyList<ChatMessage>> ListMessagesAsync(string owner,string conversation,CancellationToken cancellationToken=default)
    {
        await using var connection=await OpenConnectionAsync(cancellationToken).ConfigureAwait(false); await using var command=connection.CreateCommand();
        command.CommandText="SELECT message_id,role,status,retry_of,created_at,completed_at,version FROM messages WHERE owner_principal_id=$owner AND conversation_id=$conversation ORDER BY created_at,message_id;"; command.Parameters.AddWithValue("$owner",owner); command.Parameters.AddWithValue("$conversation",conversation);
        var values=new List<ChatMessage>(); await using(var reader=await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false)){while(await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) values.Add(new(owner,reader.GetString(0),conversation,reader.GetString(1),reader.GetString(2),ReadNullableString(reader,3),[],ParseTimestamp(reader.GetString(4)),ReadNullableTimestamp(reader,5),reader.GetInt64(6)));}
        for(var index=0;index<values.Count;index++) values[index]=values[index] with { Parts=await ReadMessagePartsAsync(connection,owner,values[index].MessageId,cancellationToken).ConfigureAwait(false) };
        return values.AsReadOnly();
    }

    private static async Task<IReadOnlyList<ChatMessagePart>> ReadMessagePartsAsync(Microsoft.Data.Sqlite.SqliteConnection connection,string owner,string message,CancellationToken token)
    {await using var command=connection.CreateCommand();command.CommandText="SELECT part_id,sequence,kind,text,capability_call_id,capability_result_id,action_id,evidence_refs_json,error_code FROM message_parts WHERE owner_principal_id=$owner AND message_id=$message ORDER BY sequence;";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$message",message);var values=new List<ChatMessagePart>();await using var reader=await command.ExecuteReaderAsync(token).ConfigureAwait(false);while(await reader.ReadAsync(token).ConfigureAwait(false))values.Add(new(reader.GetString(0),reader.GetInt64(1),reader.GetString(2),ReadNullableString(reader,3),ReadNullableString(reader,4),ReadNullableString(reader,5),ReadNullableString(reader,6),DeserializeReferences(reader.GetString(7)),ReadNullableString(reader,8)));return values.AsReadOnly();}

    public async Task AddExecutionEventAsync(PublicExecutionEvent item,CancellationToken cancellationToken=default)
    { await using var connection=await OpenConnectionAsync(cancellationToken).ConfigureAwait(false); await using var command=connection.CreateCommand(); command.CommandText="INSERT INTO execution_events(owner_principal_id,event_id,execution_id,sequence,event_type,occurred_at,message_id,capability_call_id,action_id,data_json) VALUES($owner,$id,$execution,$sequence,$type,$at,$message,$call,$action,$data);"; command.Parameters.AddWithValue("$owner",item.OwnerPrincipalId); command.Parameters.AddWithValue("$id",item.EventId); command.Parameters.AddWithValue("$execution",item.ExecutionId); command.Parameters.AddWithValue("$sequence",item.Sequence); command.Parameters.AddWithValue("$type",item.EventType); command.Parameters.AddWithValue("$at",FormatTimestamp(item.OccurredAt)); command.Parameters.AddWithValue("$message",(object?)item.MessageId??DBNull.Value); command.Parameters.AddWithValue("$call",(object?)item.CapabilityCallId??DBNull.Value); command.Parameters.AddWithValue("$action",(object?)item.ActionId??DBNull.Value); command.Parameters.AddWithValue("$data",item.DataJson); await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false); }

    public async Task AppendExecutionEventAsync(string owner,string execution,string type,string? messageId,string? capabilityCallId,string? actionId,string dataJson,DateTimeOffset now,CancellationToken token=default)
    {ProductContentValidation.Json(JsonDocument.Parse(dataJson).RootElement,nameof(dataJson),16*1024);await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="""
        INSERT INTO execution_events(owner_principal_id,event_id,execution_id,sequence,event_type,occurred_at,message_id,capability_call_id,action_id,data_json)
        SELECT $owner,$event,$execution,COALESCE(MAX(sequence),0)+1,$type,$now,$message,$call,$action,$data
        FROM execution_events WHERE owner_principal_id=$owner AND execution_id=$execution;
        """;command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$event",Guid.NewGuid().ToString("N"));command.Parameters.AddWithValue("$execution",execution);command.Parameters.AddWithValue("$type",type);command.Parameters.AddWithValue("$now",FormatTimestamp(now));command.Parameters.AddWithValue("$message",(object?)messageId??DBNull.Value);command.Parameters.AddWithValue("$call",(object?)capabilityCallId??DBNull.Value);command.Parameters.AddWithValue("$action",(object?)actionId??DBNull.Value);command.Parameters.AddWithValue("$data",dataJson);await command.ExecuteNonQueryAsync(token).ConfigureAwait(false);}

    public async Task<IReadOnlyList<PublicExecutionEvent>> ListExecutionEventsAsync(string owner,string execution,long after,CancellationToken cancellationToken=default)
    { await using var connection=await OpenConnectionAsync(cancellationToken).ConfigureAwait(false); await using var command=connection.CreateCommand(); command.CommandText="SELECT event_id,sequence,event_type,occurred_at,message_id,capability_call_id,action_id,data_json FROM execution_events WHERE owner_principal_id=$owner AND execution_id=$execution AND sequence>$after ORDER BY sequence;"; command.Parameters.AddWithValue("$owner",owner); command.Parameters.AddWithValue("$execution",execution); command.Parameters.AddWithValue("$after",after); var values=new List<PublicExecutionEvent>(); await using var reader=await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false); while(await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) values.Add(new(owner,reader.GetString(0),execution,reader.GetInt64(1),reader.GetString(2),ParseTimestamp(reader.GetString(3)),ReadNullableString(reader,4),ReadNullableString(reader,5),ReadNullableString(reader,6),reader.GetString(7))); return values.AsReadOnly(); }

    public async Task<IReadOnlyList<PublicExecutionEvent>> ListConversationEventsAsync(string owner,string conversation,long after,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="""
        SELECT e.event_id,e.execution_id,e.sequence,e.event_type,e.occurred_at,e.message_id,e.capability_call_id,e.action_id,e.data_json
        FROM execution_events e JOIN messages m ON m.owner_principal_id=e.owner_principal_id AND m.message_id=e.message_id
        WHERE e.owner_principal_id=$owner AND m.conversation_id=$conversation AND e.sequence>$after
        ORDER BY e.occurred_at,e.sequence;
        """;command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$conversation",conversation);command.Parameters.AddWithValue("$after",after);var values=new List<PublicExecutionEvent>();await using var reader=await command.ExecuteReaderAsync(token).ConfigureAwait(false);while(await reader.ReadAsync(token).ConfigureAwait(false))values.Add(new(owner,reader.GetString(0),reader.GetString(1),reader.GetInt64(2),reader.GetString(3),ParseTimestamp(reader.GetString(4)),ReadNullableString(reader,5),ReadNullableString(reader,6),ReadNullableString(reader,7),reader.GetString(8)));return values.AsReadOnly();}

    public async Task AddContextSnapshotRefAsync(string owner,string snapshotRef,string execution,string[] sourceRefs,int omitted,string[] sensitivity,DateTimeOffset now,CancellationToken token=default)
    {await using var connection=await OpenConnectionAsync(token).ConfigureAwait(false);await using var command=connection.CreateCommand();command.CommandText="INSERT INTO context_snapshot_refs(owner_principal_id,snapshot_ref,execution_id,source_refs_json,omitted_count,sensitivity_classes_json,captured_at) VALUES($owner,$ref,$execution,$sources,$omitted,$sensitivity,$at);";command.Parameters.AddWithValue("$owner",owner);command.Parameters.AddWithValue("$ref",snapshotRef);command.Parameters.AddWithValue("$execution",execution);command.Parameters.AddWithValue("$sources",Serialize(sourceRefs));command.Parameters.AddWithValue("$omitted",omitted);command.Parameters.AddWithValue("$sensitivity",Serialize(sensitivity));command.Parameters.AddWithValue("$at",FormatTimestamp(now));await command.ExecuteNonQueryAsync(token).ConfigureAwait(false);}
}