apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tessera-data
  namespace: default
  labels:
    app: tessera
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tessera-backups
  namespace: default
  labels:
    app: tessera-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi