<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Tessera.Persistence.Sqlite.Tests</RootNamespace>
    <AssemblyName>Tessera.Persistence.Sqlite.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Tessera.Persistence.Sqlite/Tessera.Persistence.Sqlite.csproj" />
  </ItemGroup>

</Project>